apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::070223344051:role/eksctl-simple-jwt-api-nodegroup-sp-NodeInstanceRole-ejl4rKl7eJf9
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::070223344051:role/simple-jwt-api-codebuild-role
      groups:
      - system:masters
      username: codebuild
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
